name: Node pnpm CI

on:
    push:
        branches:
            - "*" # matches every branch that doesn't contain a '/'
            - "*/*" # matches every branch containing a single '/'
            - "**" # matches every branch
            # - '!master'   # excludes master
    pull_request:
        branches:
            - "*" # matches every branch that doesn't contain a '/'
            - "*/*" # matches every branch containing a single '/'
            - "**" # matches every branch
            # - '!master'   # excludes master

permissions:
    contents: read

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node_version: [16.x]
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node_version }}
            - run: echo ${{github.ref}}
            - run: npm install -g pnpm
            - run: pnpm config set store-dir ~/.pnpm-store
            - run: pnpm install --strict-peer-dependencies=false
            - run: cd apps/tools-site
            - run: pnpm run lint:error
            - run: pnpm run build
              env:
                  CI: true
                  PROGRESS: none
                  NODE_ENV: test
                  NODE_OPTIONS: --max_old_space_size=4096
