name: PULL REQUEST PREVIEW

on:
  pull_request:
    branches:
      - "master" # match main branch
      - "dev" # match developer branch
      - "release/**" # matches release branch
    types:
      - opened
      - edited
      - reopened

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: build dist
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
        env:
          CI: true
          PROGRESS: none
          NODE_ENV: test
          NODE_OPTIONS: --max_old_space_size=4096
      - name: pnpm install
        run: |
          echo ${{github.ref}}
          pnpm install
      - name: Build
        run: |
          echo ${{github.workspace}}
          pnpm build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          path: apps/tools-site/dist
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: development deployment
    outputs:
      deploy-url: ${{ steps.netlify.outputs.deploy-url }}
    environment:
      name: netlify-development
      url: ${{ steps.netlify.outputs.deploy-url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist-artifact
          path: apps/tools-site/dist
      - name: Deploy to Netlify
        id: netlify
        uses: nwtgck/actions-netlify@v2.1.0
        with:
          publish-dir: "apps/tools-site/dist"
          production-deploy: false
          enable-pull-request-comment: true
          enable-commit-comment: true
          enable-commit-status: true
          overwrites-pull-request-comment: true
          enable-github-deployment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
  comment:
    runs-on: ubuntu-latest
    needs: deploy
    name: comment pull request
    steps:
      - uses: actions/checkout@v3
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🚀 Deploy on ${{ needs.deploy.outputs.deploy-url }}
