name: Deploy prod

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
        env:
          CI: true
          PROGRESS: none
          NODE_ENV: test
          NODE_OPTIONS: --max_old_space_size=4096
          NSP_NETLIFY_ACCESS_TOKEN: ${{ secrets.NSP_NETLIFY_ACCESS_TOKEN }}
          NSP_NETLIFY_PREVIEW_ID: ${{ secrets.NSP_NETLIFY_PREVIEW_ID }}
          NSP_NETLIFY_PROD_ID: ${{ secrets.NSP_NETLIFY_PROD_ID }}
      - run: echo ${{github.ref}}
      - run: npm install -g pnpm
      - run: npm install -g netlify-cli
      - run: pnpm config set store-dir ~/.pnpm-store
      - run: pnpm install --strict-peer-dependencies=false
      - run: pnpm run lint:error
      - run: pnpm run build
      - run: netlify deploy --site $NSP_NETLIFY_PROD_ID --dir dist --auth $NSP_NETLIFY_ACCESS_TOKEN --prod
